# PATHS: change accordingly
data_directory: 'Custom_data' # path to wavs and metafile directory
log_directory: 'logdir'   # weights and logs are stored here
train_data_directory: null         # optional: alternative directory where to store processed data (default is data_dir)
wav_subdir_name: 'wavs'            # subfolder in data_directory containing wavs files
metadata_filename: 'data_metafile.txt'  # name of metadata file under data_directory
session_name: null                 # session naming, can be specified in command line

# DATA
n_samples: 100000
n_test: 5
mel_start_value: .5
mel_end_value: -.5

# AUDIO
sampling_rate: 22050
n_fft: 1024
mel_channels: 80
hop_length: 256
win_length: 1024
f_min: 0
f_max: 8000
normalizer: MelGAN                 # which mel normalization to use from utils.audio.py [MelGAN or WaveRNN]
# TOKENIZER
phoneme_language: 'en'
with_stress: False                  # use stress symbols in phonemization
